---
abstract: 'Micro-blogging Client'
author:
  - 'BlueT, C<< <bluet at blue.org> >>'
distribution_type: module
generated_by: 'Module::Install version 0.80'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Jaipo
no_index:
  directory:
    - inc
    - t
recommends:
  Mac::Glue: 1.30
  Mac::Growl: 0.67
requires:
  App::Cache: 0
  Class::Accessor::Fast: 0
  Hash::Merge: 0
  Net::Twitter: 0
  Number::RecordLocator: 0
  Term::ReadLine: 0
  Test::More: 0
  Text::Table: 0
  YAML::Syck: 0
version: 0.20
